### ISSUE TITLE
404 error for URL in "week5-Cass-in-k8s/README.MD" "6. Create a KIND cluster" "1 master, 5 workers"

### ISSUE THREAD

**Issue by githubat** [DataStax-Academy/cassandra-workshop-series#23]
In the text:

We will create a Kubernetes cluster based on the following configuration 1 master, 5 workers to be able to spawn some multi nodes clusters.

The URL link for "following configuration" currently is:

https://github.com/DataStax-Academy/cassandra-workshop-series/blob/master/week5-Cass-in-k8s/01-kind-config.yaml

which resulted the 404 error.

I believe you meant to say:

https://github.com/DataStax-Academy/cassandra-workshop-series/blob/master/week5-Cass-in-k8s/setup-your-cluster/01-kind-config.yaml

My 2 cents!

**Comment by clun** [comment]
You are correct. I think it has been fixed right ?>

https://github.com/DataStax-Academy/cassandra-workshop-series/tree/master/week5-Cass-in-k8s#6-create-a-kind-cluster

You can see the command did you see it different ? We could close it now I guess.

```bash
kind create cluster --name kind-cassandra --config ./setup-your-cluster/01-kind-config.yaml
```

**Comment by githubat** [comment]
No - it's NOT FIXED YET!

It is the URL for the words "following configuration" that's wrong and needs to be fixed.

See the text...

 We will create a Kubernetes cluster based on the following configuration 1 master, 5 workers
                                                                                     ^^^^^^^^^^^^^^^^^^^^^^

If you click on the link associated with the words "following configuration" - you will get a 404 error - still.

THX!

**Comment by clun** [comment]
Got you, it was the link referred in `following configuration`, not the instruction (I was misleading). I fixed it.

Check
https://github.com/DataStax-Academy/cassandra-workshop-series/tree/master/week5-Cass-in-k8s#6-create-a-kind-cluster
